# Generated by Django 2.1.4 on 2020-05-31 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('lead', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('header', models.TextField(blank=True, default='', max_length=1000)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
    ]
