# Generated by Django 2.1.4 on 2020-05-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='footer',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='header',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
