# Generated by Django 2.1.3 on 2018-11-11 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='edited_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
