# Generated by Django 2.1.3 on 2018-11-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_auto_20181111_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='lead',
            field=models.TextField(default='example lead'),
            preserve_default=False,
        ),
    ]
