# Generated by Django 2.1.3 on 2018-12-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_auto_20181115_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='edited_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.CharField(max_length=20),
        ),
    ]
