# Generated by Django 2.1.3 on 2018-12-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0005_auto_20181207_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_caption',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='edited_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
