# Generated by Django 2.1.3 on 2018-12-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0006_auto_20181221_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
