# Generated by Django 2.1.3 on 2018-12-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0007_auto_20181223_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_caption',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
