# Generated by Django 2.1.3 on 2018-12-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0008_auto_20181223_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_caption',
        ),
    ]
