# Generated by Django 2.1.3 on 2018-12-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0009_remove_blogpost_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
