# Generated by Django 2.1.3 on 2018-12-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0010_auto_20181224_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='test-slug'),
            preserve_default=False,
        ),
    ]
