# Generated by Django 2.1.4 on 2019-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0012_auto_20181227_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
