# Generated by Django 2.1.4 on 2019-07-10 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0014_auto_20190709_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
