# Generated by Django 2.1.4 on 2019-07-16 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0015_auto_20190710_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('amazon_url', models.SlugField(blank=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('is_great', models.BooleanField(default=False)),
                ('is_best', models.BooleanField(default=False)),
            ],
        ),
    ]
