# Generated by Django 2.1.4 on 2019-07-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0016_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_best',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_great',
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('great', 'Great'), ('best', 'Best')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='amazon_url',
            field=models.CharField(max_length=1200),
        ),
    ]
