# Generated by Django 2.1.4 on 2019-07-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0017_auto_20190717_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
